In [9]:
import torch
import unsloth
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from peft import LoraConfig
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import kagglehub
import os
import shutil
import regex as re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from wordcloud import WordCloud
import numpy as np
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer
import unicodedata
from sklearn.naive_bayes import MultinomialNB
from nltk.tokenize import word_tokenize
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,accuracy_score
import pickle

tqdm.pandas()

## Charger le modèle

In [3]:
from huggingface_hub import login

login("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")

In [4]:
MODEL_NAME = "unsloth/Llama-3.2-1B-Instruct-bnb-4bit"  
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    load_in_4bit=True  # Réduit la mémoire utilisée
)

tokenizer.pad_token = tokenizer.eos_token  # Fixe le padding

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
`low_cpu_mem_usage` was None, now default to True since model is quantized.

##  Charger et préparer les données (phishing dataset)

In [17]:

data = pd.read_csv("models/merged_data.csv.zip")  

# Supprimer les colonnes inutiles
data = data.drop(columns=['Unnamed: 0'])


# Gérer les valeurs manquantes
data = data.dropna(subset=['body', 'label'])

data.head(20)

/tmp/ipykernel_51819/1170387343.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("models/merged_data.csv.zip")

,date,body,label
0,"Thu, 31 Oct 2002 02:38:20 +0000",FROM:MR. JAMES NGOLA.\nCONFIDENTIAL TEL: 233-2...,1
1,"Thu, 31 Oct 2002 05:10:00 -0000","Dear Friend,\n\nI am Mr. Ben Suleman a custom ...",1
2,"Thu, 31 Oct 2002 22:17:55 +0100",FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,1
3,"Thu, 31 Oct 2002 22:44:20 -0000",FROM HIS ROYAL MAJESTY (HRM) CROWN RULER OF EL...,1
4,"Fri, 01 Nov 2002 01:45:04 +0100","Dear sir, \n \nIt is with a heart full of hope...",1
5,"Sat, 02 Nov 2002 06:23:11 +0000",ATTENTION: ...,1
6,NaN,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1
7,"Sun, 03 Nov 2002 23:56:20 +0000",FROM: WILLIAM DRALLO.\nCONFIDENTIAL TEL: 233-2...,1
8,"Mon, 04 Nov 2002 23:41:26 -0000","CHALLENGE SECURITIES LTD.\nLAGOS, NIGERIA\n\n\...",1
9,NaN,"Dear Sir,\n\nI am Barrister Tunde Dosumu (SAN)...",1
10,"Tue, 06 Nov 2001 16:52:34 -0000",FROM: MR TEMI JOHNSON\nDEMOCRATIC REPUBLIC OF ...,1
11,"Fri, 08 Nov 2002 04:15:33 -0000",FROM THE DESK OF DR.SAM JORDAN\nTHE MANAGER\nH...,1
12,"Fri, 08 Nov 2002 10:12:26 +0100",\nSENIOR ADVOCATE OF NIGERIA\nBARR. PETER BROW...,1
13,"Mon, 11 Nov 2002 17:26:54 +0100","From;Mr.Michael Kamah and Family,\n J...",1
14,"Tue, 13 Nov 2001 16:10:50 -0000",FROM: COL. MICHAEL BUNDU. \nDEMOCRATIC REPUBLI...,1
15,"Thu, 14 Nov 2002 16:46:11 +0100","Dear Sir,\n\nA Very Good day to you \n\nI am...",1
16,"Fri, 15 Nov 2002 00:40:13 -0000",FROM: DR. ANAYO AWKA BANK MANAGER \n(UNION BAN...,1
17,"Sat, 16 Nov 2002 14:06:46 -0000","The Director,\n\n\n\n SEEKING FOR I...",1
18,"Sun, 17 Nov 2002 01:09:22 +0000",FROM: JAMES NGOLA.\nCONFIDENTIAL TEL: 233-27-5...,1
19,NaN,"$250,000 FOR INFORMATION:\n\nLEADING TO THE CR...",1

## Préparation des données

In [18]:
import pandas as pd
from multiprocessing import Pool

# Fonction de nettoyage du texte
def clean_text(text):
    '''Make text lowercase, remove text in square brackets, remove links, remove punctuation
    and remove words containing numbers.'''
    try:
        text = unicodedata.normalize("NFKC", text)  # Normalize characters
    except:
        return ""
    
    text = str(text).lower()
    sequences = ['\[.*?\]','https?://\S+|www\.\S+','<.*?>+','[%s]' % re.escape(string.punctuation),'\n','\r','\w*\d\w*']
    for sequence in sequences:
        text = re.sub(sequence, '', text)
    
    return text

# Fonction pour appliquer le nettoyage en parallèle
def apply_parallel(df, func, num_workers=4):
    with Pool(num_workers) as pool:
        return pd.Series(pool.map(func, df))

# Appliquer la fonction sur la colonne 'body' avec multiprocessing
data['body'] = apply_parallel(data['body'], clean_text, num_workers=8)

data.head()

<>:14: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\S'
<>:14: SyntaxWarning: invalid escape sequence '\w'
<>:14: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\S'
<>:14: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_51819/805414452.py:14: SyntaxWarning: invalid escape sequence '\['
  sequences = ['\[.*?\]','https?://\S+|www\.\S+','<.*?>+','[%s]' % re.escape(string.punctuation),'\n','\r','\w*\d\w*']
/tmp/ipykernel_51819/805414452.py:14: SyntaxWarning: invalid escape sequence '\S'
  sequences = ['\[.*?\]','https?://\S+|www\.\S+','<.*?>+','[%s]' % re.escape(string.punctuation),'\n','\r','\w*\d\w*']
/tmp/ipykernel_51819/805414452.py:14: SyntaxWarning: invalid escape sequence '\w'
  sequences = ['\[.*?\]','https?://\S+|www\.\S+','<.*?>+','[%s]' % re.escape(string.punctuation),'\n','\r','\w*\d\w*']

,date,body,label
0,"Thu, 31 Oct 2002 02:38:20 +0000",frommr james ngolaconfidential tel business ...,1
1,"Thu, 31 Oct 2002 05:10:00 -0000",dear friendi am mr ben suleman a custom office...,1
2,"Thu, 31 Oct 2002 22:17:55 +0100",from his royal majesty hrm crown ruler of elem...,1
3,"Thu, 31 Oct 2002 22:44:20 -0000",from his royal majesty hrm crown ruler of elem...,1
4,"Fri, 01 Nov 2002 01:45:04 +0100",dear sir it is with a heart full of hope that...,1

In [19]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Télécharger les stopwords et lemmatizer si nécessaire
nltk.download('stopwords')
nltk.download('wordnet')

# Charger les stopwords et lemmatizer
sw = set(stopwords.words('english') + ['hou', 'ect'])
lemmatizer = WordNetLemmatizer()

# Optimisation de la fonction stop_lem
def stop_lem(text):
    # Séparer les mots et filtrer les stopwords en une seule étape
    words_filtered = [lemmatizer.lemmatize(word) for word in text.split() if word not in sw]
    
    # Joindre les mots lemmatisés en une seule chaîne
    return ' '.join(words_filtered)

# Appliquer sur les données
data['body'] = data['body'].progress_apply(stop_lem)

[nltk_data] Downloading package stopwords to /home/onyxia/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/onyxia/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
100%|██████████| 164972/164972 [01:34<00:00, 1754.74it/s]

In [21]:
data.head(20)

,date,body,label
0,"Thu, 31 Oct 2002 02:38:20 +0000",frommr james ngolaconfidential tel business as...,1
1,"Thu, 31 Oct 2002 05:10:00 -0000",dear friendi mr ben suleman custom officer wor...,1
2,"Thu, 31 Oct 2002 22:17:55 +0100",royal majesty hrm crown ruler eleme kingdom ch...,1
3,"Thu, 31 Oct 2002 22:44:20 -0000",royal majesty hrm crown ruler eleme kingdom ch...,1
4,"Fri, 01 Nov 2002 01:45:04 +0100",dear sir heart full hope write seek help respe...,1
5,"Sat, 02 Nov 2002 06:23:11 +0000",attention presidentmanaging director dear sirm...,1
6,NaN,dear siri barrister tunde dosumu san solicitor...,1
7,"Sun, 03 Nov 2002 23:56:20 +0000",william dralloconfidential tel ascetained cont...,1
8,"Mon, 04 Nov 2002 23:41:26 -0000",challenge security ltdlagos nigeriaattentionma...,1
9,NaN,dear siri barrister tunde dosumu san solicitor...,1
10,"Tue, 06 Nov 2001 16:52:34 -0000",mr temi johnsondemocratic republic dear sir se...,1
11,"Fri, 08 Nov 2002 04:15:33 -0000",desk drsam jordanthe managerheadquarterfirst b...,1
12,"Fri, 08 Nov 2002 10:12:26 +0100",senior advocate nigeriabarr peter brown santel...,1
13,"Mon, 11 Nov 2002 17:26:54 +0100",frommrmichael kamah family johannesburgsouth a...,1
14,"Tue, 13 Nov 2001 16:10:50 -0000",col michael bundu democratic republic congo te...,1
15,"Thu, 14 Nov 2002 16:46:11 +0100",dear sira good day mr mariam abacha got contac...,1
16,"Fri, 15 Nov 2002 00:40:13 -0000",dr anayo awka bank manager union bank nigeria ...,1
17,"Sat, 16 Nov 2002 14:06:46 -0000",director seeking immediate assistance transfer...,1
18,"Sun, 17 Nov 2002 01:09:22 +0000",james ngolaconfidential tel dear respectfuli b...,1
19,NaN,informationleading criminal indictment offawwa...,1

In [ ]:



# Vectorisation du texte
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['body'])
y = data['label']

# Séparation des données
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
train_data = dataset["train"].train_test_split(test_size=0.1)

## Configurer LoRA pour le fine-tuning 

Pour prendre moins de temps à entrainer

In [ ]:

lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
)

## Lancer le fine-tuning

In [ ]:

model = unsloth.finetune(
    model,
    dataset=train_data["train"],
    lora_config=lora_config,
    batch_size=2,
    epochs=3,
    learning_rate=2e-4
)

NameError: name 'unsloth' is not defined

## Sauvegarder le modèle fine-tuné

In [ ]:

model.save_pretrained("phishing-llama3")
tokenizer.save_pretrained("phishing-llama3")

## Tester la génération

In [ ]:
def generate_phishing_email(prompt):
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids.cuda()
    output = model.generate(input_ids, max_length=200)
    return tokenizer.decode(output[0], skip_special_tokens=True)

test_prompt = "Write a phishing email pretending to be PayPal"
print(generate_phishing_email(test_prompt))